server:
  port: 1000

eureka:
  instance:
    hostname: peer1000
  client:
    registerWithEureka: false  #该注册中心不需要向自己注册
    fetchRegistry: false  #注册中心自己不需要去拉取访问的地址清单
    serviceUrl: #注册中心的注册地址
      defaultZone: http://peer1000:1000/eureka/
spring:
  application:
    name: eureka-server
